name: eye
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+2
environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter
  states_rebuilder: ^6.4.0
  cupertino_icons: ^1.0.6
  package_info_plus: ^9.0.0
  uuid: ^4.5.2
  flutter_native_splash: ^2.4.7
  path_provider: ^2.1.5
  path: ^1.9.1 
  hive_flutter: ^1.1.0
  collection: ^1.19.0
  objectbox: ^5.1.0
  objectbox_flutter_libs: ^5.1.0
  manager:
    path: ..//manager
  yaru: ^9.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
dev_dependencies:
  build_runner: ^2.4.15
  objectbox_generator: ^5.1.0
